### ISSUE TITLE
How similar 

### ISSUE THREAD

**Issue by robmarkcole** [SkalskiP/gradio_image_annotator#1]
Hey
docs are minimal, can you advise how similar this is to https://github.com/edgarGracia/gradio_image_annotator ?
Also any plans for integration with supervision?
Thanks

**Comment by SkalskiP** [comment]
Hi @robmarkcole 👋🏻, I'm afraid I didn't have enough time to finish working on that Gradio component. I used the `gradio_image_prompter` package. I highly recommend it.
